[project]
name = "karp-lex-types"
version = "0.7.3"
description = "The types of karp-lex"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
  { name = "Språkbanken Text", email = "sb-info@svenska.gu.se" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  # "Development Status :: 5 - Production/Stable",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: POSIX",
  "Operating System :: Unix",
  # "Operating System :: Microsoft :: Windows",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  # "uncomment if you test on these interpreters:",
  # "Programming Language :: Python :: Implementation :: IronPython",
  # "Programming Language :: Python :: Implementation :: Jython",
  # "Programming Language :: Python :: Implementation :: Stackless",
  "Topic :: Utilities",
]
dependencies = [
  "pydantic>=2.5.3",
  "python-ulid>=4.0.1",
]

[project.urls]
Documentation = "https://github.com/spraakbanken/karp-lex-types"
Homepage = "https://spraakbanken.gu.se"
Issues = "https://github.com/spraakbanken/karp-lex-types/issues"
Repository = "https://github.com/spraakbanken/karp-lex-types"

[dependency-groups]
dev = [
  "pytest>=9.1.1",
  "pytest-cov>=7.1.0",
  "ruff>=0.16.7",
  "ty>=0.0.81",
]

[build-system]
requires = ["uv_build>=0.12.0,<0.13"]
build-backend = "uv_build"

[tool.uv]
exclude-newer = "P7D"

[tool.uv.build-backend]
module-name = "karp_lex_types"
