[project]
name = "karp-lex-types"
version = "0.7.3"
description = "The types of karp-lex"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [
  { name = "Språkbanken Text", email = "sb-info@svenska.gu.se" },
]
dependencies = [
    "pydantic>=2.5.3",
    "python-ulid>=4.0.1",
]

[project.urls]
Documentation = "https://github.com/spraakbanken/karp-lex-types"
Homepage = "https://spraakbanken.gu.se"
Issues = "https://github.com/spraakbanken/karp-lex-types/issues"
Repository = "https://github.com/spraakbanken/karp-lex-types"

[dependency-groups]
dev = [
  "pytest>=9.1.1",
  "pytest-cov>=7.1.0",
  "ruff>=0.16.7",
]

[build-system]
requires = ["uv_build>=0.12.0,<0.13"]
build-backend = "uv_build"

[tool.uv]
exclude-newer = "P7D"

[tool.uv.build-backend]
module-name = "karp_lex_types"
